### ISSUE TITLE
Can't save Arrays of Resources

### ISSUE THREAD

**Issue by AdamKormos** [AdamKormos/SaveMadeEasy#1]
Right now, when you try to save an array of Resources, it won't work because the code only makes it so that it parses Resources as Dictionaries when the saved object's type is a Resource. However, even if code detected an Array element is a Resource, loading it at startup and assigning it to a Resource would crash because Resources are actually saved as Dictionaries.
The latter issue can be resolved by creating the inverse of _resource_to_dict, something like _dict_to_resource but if the plugin has the objective of supporting actual Resource save-load, we would need a flag in each saved Dictionary to see whether it is _actually_ a Dictionary, or just a Resource. We also need to be aware of recursion in this instance.

**Sample code to reproduce (assuming the project has the plugin downloaded):**
```
extends Node2D
var items = Array()
# Called when the node enters the scene tree for the first time.
func _ready():
  var item = TestResource.new()
  items.append(item)
  $Label.text = "Press Load"

func _on_save_button_pressed():
  SaveSystem.set_var("items",items)
  SaveSystem.save()
  $Label.text = str(items)
```

Spotted & submitted by https://twitter.com/gferrari

**Comment by AdamKormos** [comment]
Temporary solution for loading data directly into a Resource as of the latest update:

```
	var loadedItems = SaveSystem.get_var("items")
	if(loadedItems != null):
		for i in range(loadedItems.size()):
			loadedItems[i] = _dict_to_resource(loadedItems[i], TestResource.new())
	print(loadedItems)
 
	var savedItems := []
	if(loadedItems != null):
		for item in loadedItems:
			savedItems.append(_resource_to_dict(item))
 
	savedItems.append(_resource_to_dict(TestResource.new()))
	SaveSystem.set_var("items", savedItems)
	SaveSystem.save()
```

**Comment by Loppansson** [comment]
Hi!:) I'm facing the same problem; rn i'm building a sanbox building game where i want to have different save slot's and a bunch of different types of data stored, and to do this i'm thinking of using Resources with Resources. Like a SaveSlot resource, containing an array of different resources. One could might be a BuiltObjects resource, which in turn would contain an array of BuiltObject resource.

Does the temporary solution work for that? And how do i use it?

Thank you for the amazing plug-in btw!:) It has saved me so much time not having to build an entire save system from scratch 🙏

**Comment by AdamKormos** [comment]
Hello! Unfortunately the temporary solution doesn't fix this issue, however, once I approve your PR and get around to it, I will implement a method that allows Resource arrays :)

**Comment by Loppansson** [comment]
^^

**Comment by AdamKormos** [comment]
A workaround just came to mind -
You can index the save values' keys, rather than using one key entry to store the entire array. For example:
```
# Saves an array of resources at save keys "item0", "item1" and so on...
for i in range(savedItems.size()):
  SaveSystem.set_var("item" + str(i), savedItems[i])
```

**Comment by AdamKormos** [comment]
Recent commit solves this issue. :)

**Comment by Loppansson** [comment]
Eeey! Great work!^^

**Comment by AdamKormos** [comment]
Thanks mate! I finally got around to it haha
Fortunately it was not a lengthy process, sorry for the wait. :)

**Comment by Loppansson** [comment]
Of course! And no worries;it's tricky to find time some times haha

**Comment by AdamKormos** [comment]
Trueee
Moving onwards to what I imagine as AudioMadeEasy :D I really wish there was a convenient audio management plugin easy enough to use, similar to Godot 3's SoundManager, but even that crashed many of our projects randomly so I had to end up using parts of it to simplify it.

**Comment by Loppansson** [comment]
Ooh! That sounds nice goal! I've not done to much work with sound in godot yet, but if there's no simple way to work with it in Godot, a plugin like that sounds great:)

**Comment by AdamKormos** [comment]
It is actually quite simple, but surprisingly, no plugins deal with it - the easy and manageable way -, as far as I'm aware. It can get really complicated though, but I assume most games are okay with basic functionalities such as volume setting, looping and binding sounds to a certain bus.

**Comment by Loppansson** [comment]
Ah, that's fair!:)
