### ISSUE TITLE
missing from the asset libs

### ISSUE THREAD

**Issue by samjaninf** [AdamKormos/SaveMadeEasy#4]
Is this plugin available for godot 4.2? I haven't been able to find it in the asset library.

**Comment by AdamKormos** [comment]
Hello! Hmmm I think I also seemed to not find some plugins in 4.2. I probably need to upload mine to the assetlib website with 4.2 support too, or something like that. In any case, you can straight up download the repo's addons/save_system folder. :) It should work as intended as long as you place the contents of the folder into a directory of a similar path ("addons/save_system").
