### ISSUE TITLE
Add a new Save docker

### ISSUE THREAD

**Issue by JUSTCAMH** [AdamKormos/SaveMadeEasy#5]
Hey, thanks for this awesome asset, it's been really handy so far! I just wanted to leave a feature request based on something that would help my workflow; for a new docker that provides buttons and info related to saving. I'd like to have a button I can press in editor to clear the save state (which would simply call SaveSystem.delete_all() and SaveSystem.save()). Hopefully I could use this button both whilst playing and in the editor. Would also be handy to have a toggle to automatically delete save data when entering play so that I can test the game from the start and ignore saving. 

And the feature that would be most helpful for this docker is tools to debug the save. This could simply be a button to open the save file with a text editor, or otherwise to open the filepath of the save (it would also be handy if the github readme mentioned the save file location). And I'm not sure if this would be possible, but perhaps you could make a custom inspector that shows all the keys and values of the save in the editor in a similar way to the normal inspector you'd use for nodes / resources. This would be handy as the default save format is encrypted, and whilst this can be disabled, it still formats the save as a single line, rather than with indented lines, making it hard to read and debug. Viewing the save file keys and values in editor would be a fast and easy way to debug saves.

**Comment by AdamKormos** [comment]
Hello! Thank you for using the plugin, I'm glad it's helpful. :) I've had a docker on mind, honestly the reason why I haven't gotten around to such expansions is that my initial drive was to provide something Unity does with PlayerPrefs - which is just saving primitive values. 
Now, the plugin has become something much greater and more ambitious, and I'm happy to see it evolve. I will keep making improvements like the ones you've pointed out, absolutely.
I've just found out there is an easy way to line-break the dictionary, by calling the JSON.stringify method with "\t" as the indent parameter. I will push that right now. :)
The save file location is the default user directory (user://), which is `C:\Users\UserName\AppData\Roaming\Godot\app_userdata` - I'll add that to the readme.

**Comment by JUSTCAMH** [comment]
I just tried making my own EditorScript that clears the save, though since the save system isn't marked as a tool script, functions on the SaveSystem can only be accessed at runtime. So having some inbuilt way to clear the save, whether that be a docker or maybe Project > Tools > Clear Save button would be handy to have

**Comment by AdamKormos** [comment]
You _can_ make the script run in the editor, probably with no hiccups. I cannot promise adding any editor functionalities in the near future, but I'm certainly keeping these in mind.

**Comment by AdamKormos** [comment]
I've had trouble connecting a docker to the plugin to communicate with certain parts of the demanded functionality, but now the SaveSystem AutoLoad is a scene, and you have variables there to adjust, as well as a preview of the save data in the form of a Dictionary. Will mark this closed.
